/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package algoritmoBuyi;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Collections;

/**
 *
 * @author Dons
 */
public class BullyFrame extends javax.swing.JFrame {
    int id=0;
    int desicion=0;
    ArrayList<Integer> arr;
    /** Creates new form BullyFrame */
    public BullyFrame() {
        initComponents();
        arr=new ArrayList<>();
        this.f1.setVisible(false);
        this.f2.setVisible(false);
        this.f3.setVisible(false);
        this.f4.setVisible(false);
        this.f5.setVisible(false);
        this.f6.setVisible(false);
        this.f7.setVisible(false);
        this.f8.setVisible(false);
        this.e1.setVisible(false);
        this.e2.setVisible(false);
        this.e3.setVisible(false);
        this.e4.setVisible(false);
        this.e5.setVisible(false);
        this.e6.setVisible(false);
        this.e7.setVisible(false);
        this.e8.setVisible(false);
        for(int i=1;i<9;i++){
              arr.add(i);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        f1 = new javax.swing.JButton();
        c1 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        e1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        f2 = new javax.swing.JButton();
        c2 = new javax.swing.JButton();
        t2 = new javax.swing.JTextField();
        e2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        f3 = new javax.swing.JButton();
        c3 = new javax.swing.JButton();
        t3 = new javax.swing.JTextField();
        e3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        f4 = new javax.swing.JButton();
        c4 = new javax.swing.JButton();
        t4 = new javax.swing.JTextField();
        e4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        f5 = new javax.swing.JButton();
        c5 = new javax.swing.JButton();
        t5 = new javax.swing.JTextField();
        e5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        f6 = new javax.swing.JButton();
        c6 = new javax.swing.JButton();
        t6 = new javax.swing.JTextField();
        e6 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        f7 = new javax.swing.JButton();
        c7 = new javax.swing.JButton();
        t7 = new javax.swing.JTextField();
        e7 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        f8 = new javax.swing.JButton();
        c8 = new javax.swing.JButton();
        t8 = new javax.swing.JTextField();
        e8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        f1.setText("Fallo");
        f1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f1ActionPerformed(evt);
            }
        });

        c1.setText("Cordinador");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        t1.setEditable(false);
        t1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });

        e1.setText("Entrar");
        e1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(t1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(e1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(c1)
                                    .addComponent(f1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(f1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(e1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        f2.setText("Fallo");
        f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f2ActionPerformed(evt);
            }
        });

        c2.setText("Cordinador");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });

        t2.setEditable(false);
        t2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });

        e2.setText("Entrar");
        e2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t2)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(c2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(f2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(e2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(f2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(e2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        f3.setText("Fallo");
        f3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f3ActionPerformed(evt);
            }
        });

        c3.setText("Cordinador");
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });

        t3.setEditable(false);
        t3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });

        e3.setText("Entrar");
        e3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(f3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(c3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(e3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(f3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(c3)
                .addGap(1, 1, 1)
                .addComponent(e3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        f4.setText("Fallo");
        f4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f4ActionPerformed(evt);
            }
        });

        c4.setText("Cordinador");
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });

        t4.setEditable(false);
        t4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });

        e4.setText("Entrar");
        e4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t4)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(f4, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                        .addComponent(c4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(e4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(f4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(e4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));

        f5.setText("Fallo");
        f5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f5ActionPerformed(evt);
            }
        });

        c5.setText("Cordinador");
        c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5ActionPerformed(evt);
            }
        });

        t5.setEditable(false);
        t5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });

        e5.setText("Entrar");
        e5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t5)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(f5, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(c5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(e5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(f5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(e5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel6.setBackground(new java.awt.Color(255, 204, 204));

        f6.setText("Fallo");
        f6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f6ActionPerformed(evt);
            }
        });

        c6.setText("Cordinador");
        c6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c6ActionPerformed(evt);
            }
        });

        t6.setEditable(false);
        t6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });

        e6.setText("Entrar");
        e6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t6)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(f6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(c6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(e6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(f6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(c6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(e6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 204, 204));

        f7.setText("Fallo");
        f7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f7ActionPerformed(evt);
            }
        });

        c7.setText("Cordinador");
        c7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c7ActionPerformed(evt);
            }
        });

        t7.setEditable(false);
        t7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7ActionPerformed(evt);
            }
        });

        e7.setText("Entrar");
        e7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t7)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(f7, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(e7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(c7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(f7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(e7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(255, 204, 204));

        f8.setText("Fallo");
        f8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f8ActionPerformed(evt);
            }
        });

        c8.setText("Cordinado");
        c8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c8ActionPerformed(evt);
            }
        });

        t8.setEditable(false);
        t8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t8ActionPerformed(evt);
            }
        });

        e8.setText("Entrar");
        e8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t8)
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(f8, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(c8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(e8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(f8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(e8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setText("Proceso 1");

        jLabel2.setText("Proceso 2");

        jLabel3.setText("Proceso 3");

        jLabel4.setText("Proceso 4");

        jLabel5.setText("Proceso 5");

        jLabel6.setText("Proceso 6");

        jLabel7.setText("Proceso 7");

        jLabel8.setText("Proceso 8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel5)
                        .addGap(181, 181, 181)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(57, 57, 57))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel7)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        // Boton 4 cordinador
        id=4;
        textArea.append("El cordinador es el proceso 4"+"\n");
        t4.setText("CORDINADOR");
        t4.setBackground(Color.GREEN);
        t1.setText("Proceso 1");
        t2.setText("Proceso 2");
        t3.setText("Proceso 3");
        t6.setText("Proceso 6");
        t7.setText("Proceso 7");
        t8.setText("Proceso 8");
        t5.setText("Proceso 5");
        this.c1.setVisible(false);
        this.c2.setVisible(false);
        this.c3.setVisible(false);
        this.c4.setVisible(false);
        this.c5.setVisible(false);
        this.c6.setVisible(false);
        this.c7.setVisible(false);
        this.c8.setVisible(false);
         this.f1.setVisible(true);
        this.f2.setVisible(true);
        this.f3.setVisible(true);
        this.e4.setVisible(true);
        this.e4.setEnabled(false);//Boton no se púede tocar
       
        this.f4.setVisible(false);
        this.f5.setVisible(true);
        this.f6.setVisible(true);
        this.f7.setVisible(true);
        this.f8.setVisible(true);
    }//GEN-LAST:event_c4ActionPerformed

    private void f7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f7ActionPerformed
        // fallo proceso 7
        //Aqui se detecta que fallara 
        for (int i = 1; i <arr.size(); i++) {
            if(arr.get(i)==this.id) arr.remove(i);
        }
        textArea.append("Proceso 7 detecto el fallo."+"\n");
        //Aqui error ....
        //Todos los que esten afuera del grupo acticar entrada.
        //e7.setEnabled(true);
        textArea.append("El proceso "+this.id+" sale del grupo."+"\n");
        switch(this.id){
            case 1:{
                e1.setEnabled(true);
                  t1.setText("DESACTIVADO");
                  t1.setBackground(Color.RED);
                break;
            }
            case 3:{
                e3.setEnabled(true);
                  t3.setText("DESACTIVADO");
                  t3.setBackground(Color.RED);
                break;
            }
            case 4:{
                e4.setEnabled(true);
                  t4.setText("DESACTIVADO");
                  t4.setBackground(Color.RED);
                break;
            }
            case 5:{
                e5.setEnabled(true);
                  t5.setText("DESACTIVADO");
                  t5.setBackground(Color.RED);
                break;
            }
            case 6:{
                e6.setEnabled(true);
                  t6.setText("DESACTIVADO");
                  t6.setBackground(Color.RED);
                break;
            }
            case 2:{
                  e2.setEnabled(true);
                  t2.setText("DESACTIVADO");
                  t2.setBackground(Color.RED);
                break;
            }
            case 8:{
                e8.setEnabled(true);
                  t8.setText("DESACTIVADO");
                  t8.setBackground(Color.RED);
                break;
            }
            case 7:{
                e7.setEnabled(true);
                  t7.setText("DESACTIVADO");
                  t7.setBackground(Color.RED);
                break;
            }
        }
        //Ordeno el arreglo para tomar la posicion mas grande
        Collections.sort(arr); //Para ordenar elementos.
        for (int j = 7; j < arr.size(); j++) {
            //System.out.println(arr.get(j));
            textArea.append("El proceso "+arr.get(j)+" responde con OK."+"\n");
        }
        textArea.append("El proceso "+arr.get(arr.size()-1)+" es el nuevo cordinador."+"\n");
        switch(arr.get(arr.size()-1)){
            case 1:{
                id=1;
                t1.setText("CORDINADOR");
                t1.setBackground(Color.GREEN);
                f1.setVisible(false);
                 
                e1.setVisible(true);
                e1.setEnabled(false);
                break;
            }
            case 3:{
                id=3;
                t3.setText("CORDINADOR");
                t3.setBackground(Color.GREEN);
                f3.setVisible(false);
                e3.setVisible(true);
                e3.setEnabled(false);
                break;
            }
            case 4:{
                id=4;
                t4.setText("CORDINADOR");
                t4.setBackground(Color.GREEN);
                f4.setVisible(false);
                e4.setVisible(true);
                e4.setEnabled(false);
                break;
            }
            case 5:{
                id=5;
                t5.setText("CORDINADOR");
                t5.setBackground(Color.GREEN);
                f5.setVisible(false);
                e5.setVisible(true);
                e5.setEnabled(false);
                break;
            }
            case 6:{
                id=6;
                t6.setText("CORDINADOR");
                t6.setBackground(Color.GREEN);
                f6.setVisible(false);
                e6.setVisible(true);
                e6.setEnabled(false);
                break;
            }
            case 2:{
                id=2;
                t2.setText("CORDINADOR");
                t2.setBackground(Color.GREEN);
                f2.setVisible(false);
                e2.setVisible(true);
                e2.setEnabled(false);
                break;
            }
            case 8:{
                id=8;
                t8.setText("CORDINADOR");
                t8.setBackground(Color.GREEN);
                f8.setVisible(false);
                e8.setVisible(true);
                e8.setEnabled(false);
                break;
            } 
            case 7:{
                id=7;
                t7.setText("CORDINADOR");
                t7.setBackground(Color.GREEN);
                f7.setVisible(false);
                e7.setVisible(true);
                e7.setEnabled(false);
                break;
            } 
        }
        arr.remove(arr.size()-1);
    }//GEN-LAST:event_f7ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // Boton 1: cordinador
        id=1;
        textArea.append("El cordinador es el proceso 1"+"\n");
        t1.setText("CORDINADOR");
        t1.setBackground(Color.GREEN);
        t4.setText("Proceso 4");
        t2.setText("Proceso 2");
        t3.setText("Proceso 3");
        t6.setText("Proceso 6");
        t7.setText("Proceso 7");
        t8.setText("Proceso 8");
        t5.setText("Proceso 5");
        this.c1.setVisible(false);
        this.c2.setVisible(false);
        this.c3.setVisible(false);
        this.c4.setVisible(false);
        this.c5.setVisible(false);
        this.c6.setVisible(false);
        this.c7.setVisible(false);
        this.c8.setVisible(false);
        this.f2.setVisible(true);
        this.f3.setVisible(true);
        this.f4.setVisible(true);
        this.f5.setVisible(true);
        this.f6.setVisible(true);
        this.f7.setVisible(true);
        this.f8.setVisible(true);
        this.e1.setVisible(true);
        this.e1.setEnabled(false);//Boton no se púede tocar
       
        this.f1.setVisible(false);
    }//GEN-LAST:event_c1ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        //  Boton 2 cordinador
        id=2;
        textArea.append("El cordinador es el proceso 2"+"\n");
        t2.setText("CORDINADOR");
        t2.setBackground(Color.GREEN);
        t1.setText("Proceso 1");
        t4.setText("Proceso 4");
        t3.setText("Proceso 3");
        t6.setText("Proceso 6");
        t7.setText("Proceso 7");
        t8.setText("Proceso 8");
        t5.setText("Proceso 5");
        this.c1.setVisible(false);
        this.c2.setVisible(false);
        this.c3.setVisible(false);
        this.c4.setVisible(false);
        this.c5.setVisible(false);
        this.c6.setVisible(false);
        this.c7.setVisible(false);
        this.c8.setVisible(false);
         this.f1.setVisible(true);
        this.f3.setVisible(true);
        this.f4.setVisible(true);
        this.f5.setVisible(true);
        this.f6.setVisible(true);
        this.f7.setVisible(true);
        this.f8.setVisible(true);
        this.e2.setVisible(true);
        this.e2.setEnabled(false);//Boton no se púede tocar
       
        this.f2.setVisible(false);
    }//GEN-LAST:event_c2ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // Boton 3 cordinador
        id=3;
        textArea.append("El cordinador es el proceso 3"+"\n");
        t3.setText("CORDINADOR");
        t3.setBackground(Color.GREEN);
        t1.setText("Proceso 1");
        t2.setText("Proceso 2");
        t4.setText("Proceso 4");
        t6.setText("Proceso 6");
        t7.setText("Proceso 7");
        t8.setText("Proceso 8");
        t5.setText("Proceso 5");
        this.c1.setVisible(false);
        this.c2.setVisible(false);
        this.c3.setVisible(false);
        this.c4.setVisible(false);
        this.c5.setVisible(false);
        this.c6.setVisible(false);
        this.c7.setVisible(false);
        this.c8.setVisible(false);
         this.f1.setVisible(true);
        this.f2.setVisible(true);
        this.f4.setVisible(true);
        this.f5.setVisible(true);
        this.f6.setVisible(true);
        this.f7.setVisible(true);
        this.f8.setVisible(true);
        
        this.e3.setVisible(true);
        this.e3.setEnabled(false);//Boton no se púede tocar
       
        this.f3.setVisible(false);
    }//GEN-LAST:event_c3ActionPerformed

    private void c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5ActionPerformed
        // boton 5 cordiandor
        id=5;
        textArea.append("El cordinador es el proceso 5"+"\n");
        t5.setText("CORDINADOR");
        t5.setBackground(Color.GREEN);
        t1.setText("Proceso 1");
        t2.setText("Proceso 2");
        t3.setText("Proceso 3");
        t6.setText("Proceso 6");
        t7.setText("Proceso 7");
        t8.setText("Proceso 8");
        t4.setText("Proceso 4");
        this.c1.setVisible(false);
        this.c2.setVisible(false);
        this.c3.setVisible(false);
        this.c4.setVisible(false);
        this.c5.setVisible(false);
        this.c6.setVisible(false);
        this.c7.setVisible(false);
        this.c8.setVisible(false);
         this.f1.setVisible(true);
        this.f2.setVisible(true);
        this.f3.setVisible(true);
        this.f4.setVisible(true);
        this.f6.setVisible(true);
        this.f7.setVisible(true);
        this.f8.setVisible(true);
        this.e5.setVisible(true);
        this.e5.setEnabled(false);//Boton no se púede tocar
       
        this.f5.setVisible(false);
    }//GEN-LAST:event_c5ActionPerformed

    private void c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c6ActionPerformed
        // Boton 6 cordiandor
        id=6;
        textArea.append("El cordinador es el proceso 6"+"\n");
        t6.setText("CORDINADOR");
        t6.setBackground(Color.GREEN);
        t1.setText("Proceso 1");
        t2.setText("Proceso 2");
        t3.setText("Proceso 3");
        t4.setText("Proceso 4");
        t7.setText("Proceso 7");
        t8.setText("Proceso 8");
        t5.setText("Proceso 5");
        this.c1.setVisible(false);
        this.c2.setVisible(false);
        this.c3.setVisible(false);
        this.c4.setVisible(false);
        this.c5.setVisible(false);
        this.c6.setVisible(false);
        this.c7.setVisible(false);
        this.c8.setVisible(false);
        this.f1.setVisible(true);
        this.f2.setVisible(true);
        this.f3.setVisible(true);
        this.f4.setVisible(true);
        this.f5.setVisible(true);
        this.f7.setVisible(true);
        this.f8.setVisible(true);
        
       this.e6.setVisible(true);
        this.e6.setEnabled(false);//Boton no se púede tocar
       
        this.f6.setVisible(false);
    }//GEN-LAST:event_c6ActionPerformed

    private void c7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c7ActionPerformed
        // Boton 7 cordinador
        id=7;
        textArea.append("El cordinador es el proceso 7"+"\n");
        t7.setText("CORDINADOR");
        t7.setBackground(Color.GREEN);
        t1.setText("Proceso 1");
        t2.setText("Proceso 2");
        t3.setText("Proceso 3");
        t6.setText("Proceso 6");
        t4.setText("Proceso 4");
        t8.setText("Proceso 8");
        t5.setText("Proceso 5");
        this.c1.setVisible(false);
        this.c2.setVisible(false);
        this.c3.setVisible(false);
        this.c4.setVisible(false);
        this.c5.setVisible(false);
        this.c6.setVisible(false);
        this.c7.setVisible(false);
        this.c8.setVisible(false);
         this.f1.setVisible(true);
        this.f2.setVisible(true);
        this.f3.setVisible(true);
        this.f4.setVisible(true);
        this.f5.setVisible(true);
        this.f6.setVisible(true);
        this.f8.setVisible(true);
       this.e7.setVisible(true);
        this.e7.setEnabled(false);//Boton no se púede tocar
        this.f7.setVisible(false);
    }//GEN-LAST:event_c7ActionPerformed

    private void c8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c8ActionPerformed
        // Cordinador 8 boton
        id=8;
        textArea.append("El cordinador es el proceso 8"+"\n");
        t8.setText("CORDINADOR");
        t8.setBackground(Color.GREEN);
        t1.setText("Proceso 1");
        t2.setText("Proceso 2");
        t3.setText("Proceso 3");
        t6.setText("Proceso 6");
        t7.setText("Proceso 7");
        t4.setText("Proceso 4");
        t5.setText("Proceso 5");
        this.c1.setVisible(false);
        this.c2.setVisible(false);
        this.c3.setVisible(false);
        this.c4.setVisible(false);
        this.c5.setVisible(false);
        this.c6.setVisible(false);
        this.c7.setVisible(false);
        this.c8.setVisible(false);
         this.f1.setVisible(true);
        this.f2.setVisible(true);
        this.f3.setVisible(true);
        this.f4.setVisible(true);
        this.f5.setVisible(true);
        this.f6.setVisible(true);
        this.f7.setVisible(true);

       this.e8.setVisible(true);
        this.e8.setEnabled(false);//Boton no se púede tocar
       
        this.f8.setVisible(false);
    }//GEN-LAST:event_c8ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t6ActionPerformed

    private void t7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t7ActionPerformed

    private void t8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t8ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void f1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f1ActionPerformed
        //fallo proceso 1
        //Aqui se detecta que fallara 
        for (int i = 1; i <arr.size(); i++) {
            if(arr.get(i)==this.id) arr.remove(i);
        }
        textArea.append("Proceso 1 detecto el fallo."+"\n");
        //Aqui error ....
        //Todos los que esten afuera del grupo acticar entrada.
        //e7.setEnabled(true);
        textArea.append("El proceso "+this.id+" sale del grupo."+"\n");
        switch(this.id){
            case 2:{
                e2.setEnabled(true);
                  t2.setText("DESACTIVADO");
                  t2.setBackground(Color.RED);
                break;
            }
            case 3:{
                e3.setEnabled(true);
                  t3.setText("DESACTIVADO");
                  t3.setBackground(Color.RED);
                break;
            }
            case 4:{
                e4.setEnabled(true);
                  t4.setText("DESACTIVADO");
                  t4.setBackground(Color.RED);
                break;
            }
            case 5:{
                e5.setEnabled(true);
                  t5.setText("DESACTIVADO");
                  t5.setBackground(Color.RED);
                break;
            }
            case 6:{
                e6.setEnabled(true);
                  t6.setText("DESACTIVADO");
                  t6.setBackground(Color.RED);
                break;
            }
            case 7:{
                  e7.setEnabled(true);
                  t7.setText("DESACTIVADO");
                  t7.setBackground(Color.RED);
                break;
            }
            case 8:{
                e8.setEnabled(true);
                  t8.setText("DESACTIVADO");
                  t8.setBackground(Color.RED);
                break;
            }
        }
        //Ordeno el arreglo para tomar la posicion mas grande
        Collections.sort(arr); //Para ordenar elementos.
        for (int j = 1; j < arr.size(); j++) {
            //System.out.println(arr.get(j));
            textArea.append("El proceso "+arr.get(j)+" responde con OK."+"\n");
        }
        textArea.append("El proceso "+arr.get(arr.size()-1)+" es el nuevo cordinador."+"\n");
        switch(arr.get(arr.size()-1)){
            case 2:{
                id=2;
                t2.setText("CORDINADOR");
                t2.setBackground(Color.GREEN);
                f2.setVisible(false);
                 
                e2.setVisible(true);
                e2.setEnabled(false);
                break;
            }
            case 3:{
                id=3;
                t3.setText("CORDINADOR");
                t3.setBackground(Color.GREEN);
                f3.setVisible(false);
                e3.setVisible(true);
                e3.setEnabled(false);
                break;
            }
            case 4:{
                id=4;
                t4.setText("CORDINADOR");
                t4.setBackground(Color.GREEN);
                f4.setVisible(false);
                e4.setVisible(true);
                e4.setEnabled(false);
                break;
            }
            case 5:{
                id=5;
                t5.setText("CORDINADOR");
                t5.setBackground(Color.GREEN);
                f5.setVisible(false);
                e5.setVisible(true);
                e5.setEnabled(false);
                break;
            }
            case 6:{
                id=6;
                t6.setText("CORDINADOR");
                t6.setBackground(Color.GREEN);
                f6.setVisible(false);
                e6.setVisible(true);
                e6.setEnabled(false);
                break;
            }
            case 7:{
                id=7;
                t7.setText("CORDINADOR");
                t7.setBackground(Color.GREEN);
                f7.setVisible(false);
                e7.setVisible(true);
                e7.setEnabled(false);
                break;
            }
            case 8:{
                id=8;
                t8.setText("CORDINADOR");
                t8.setBackground(Color.GREEN);
                f8.setVisible(false);
                e8.setVisible(true);
                e8.setEnabled(false);
                break;
            } 
        }
        arr.remove(arr.size()-1);
         
    }//GEN-LAST:event_f1ActionPerformed

    private void f2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f2ActionPerformed
        //fallo2
        //Aqui se detecta que fallara 
        for (int i = 1; i <arr.size(); i++) {
            if(arr.get(i)==this.id) arr.remove(i);
        }
        textArea.append("Proceso 2 detecto el fallo."+"\n");
        //Aqui error ....
        //Todos los que esten afuera del grupo acticar entrada.
        //e7.setEnabled(true);
        textArea.append("El proceso "+this.id+" sale del grupo."+"\n");
        switch(this.id){
            case 1:{
                e1.setEnabled(true);
                  t1.setText("DESACTIVADO");
                  t1.setBackground(Color.RED);
                break;
            }
            case 3:{
                e3.setEnabled(true);
                  t3.setText("DESACTIVADO");
                  t3.setBackground(Color.RED);
                break;
            }
            case 4:{
                e4.setEnabled(true);
                  t4.setText("DESACTIVADO");
                  t4.setBackground(Color.RED);
                break;
            }
            case 5:{
                e5.setEnabled(true);
                  t5.setText("DESACTIVADO");
                  t5.setBackground(Color.RED);
                break;
            }
            case 6:{
                e6.setEnabled(true);
                  t6.setText("DESACTIVADO");
                  t6.setBackground(Color.RED);
                break;
            }
            case 7:{
                  e7.setEnabled(true);
                  t7.setText("DESACTIVADO");
                  t7.setBackground(Color.RED);
                break;
            }
            case 8:{
                e8.setEnabled(true);
                  t8.setText("DESACTIVADO");
                  t8.setBackground(Color.RED);
                break;
            }
        }
        //Ordeno el arreglo para tomar la posicion mas grande
        Collections.sort(arr); //Para ordenar elementos.
        for (int j = 2; j < arr.size(); j++) {
            //System.out.println(arr.get(j));
            textArea.append("El proceso "+arr.get(j)+" responde con OK."+"\n");
        }
        textArea.append("El proceso "+arr.get(arr.size()-1)+" es el nuevo cordinador."+"\n");
        switch(arr.get(arr.size()-1)){
            case 1:{
                id=1;
                t1.setText("CORDINADOR");
                t1.setBackground(Color.GREEN);
                f1.setVisible(false);
                 
                e1.setVisible(true);
                e1.setEnabled(false);
                break;
            }
            case 3:{
                id=3;
                t3.setText("CORDINADOR");
                t3.setBackground(Color.GREEN);
                f3.setVisible(false);
                e3.setVisible(true);
                e3.setEnabled(false);
                break;
            }
            case 4:{
                id=4;
                t4.setText("CORDINADOR");
                t4.setBackground(Color.GREEN);
                f4.setVisible(false);
                e4.setVisible(true);
                e4.setEnabled(false);
                break;
            }
            case 5:{
                id=5;
                t5.setText("CORDINADOR");
                t5.setBackground(Color.GREEN);
                f5.setVisible(false);
                e5.setVisible(true);
                e5.setEnabled(false);
                break;
            }
            case 6:{
                id=6;
                t6.setText("CORDINADOR");
                t6.setBackground(Color.GREEN);
                f6.setVisible(false);
                e6.setVisible(true);
                e6.setEnabled(false);
                break;
            }
            case 7:{
                id=7;
                t7.setText("CORDINADOR");
                t7.setBackground(Color.GREEN);
                f7.setVisible(false);
                e7.setVisible(true);
                e7.setEnabled(false);
                break;
            }
            case 8:{
                id=8;
                t8.setText("CORDINADOR");
                t8.setBackground(Color.GREEN);
                f8.setVisible(false);
                e8.setVisible(true);
                e8.setEnabled(false);
                break;
            } 
        }
        arr.remove(arr.size()-1);
         

    }//GEN-LAST:event_f2ActionPerformed

    private void e4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e4ActionPerformed
        //entrar proceso 4
        arr.add(4);
        //Ordeno el arreglo para tomar la posicion mas grande
        Collections.sort(arr); //Para ordenar elementos.
        for (int i = 0; i < arr.size(); i++) {
            System.out.println(arr.get(i));
        }
        textArea.append("Entro al grupo el proceso 4."+"\n");
        f4.setVisible(true);
        e4.setVisible(false);
        e4.setEnabled(true);
        t4.setText("Proceso 4");
        t4.setBackground(Color.WHITE);
    }//GEN-LAST:event_e4ActionPerformed

    private void e7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e7ActionPerformed
        // Entrar proceso 7
         arr.add(7);
        //Ordeno el arreglo para tomar la posicion mas grande
        Collections.sort(arr); //Para ordenar elementos.
        for (int i = 0; i < arr.size(); i++) {
            System.out.println(arr.get(i));
        }
        textArea.append("Entro al grupo el proceso 7."+"\n");
        f7.setVisible(true);
        e7.setVisible(false);
        e7.setEnabled(true);
        t7.setText("Proceso 7");
        t7.setBackground(Color.WHITE);
    }//GEN-LAST:event_e7ActionPerformed

    private void e8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e8ActionPerformed
        // Entrar proceso 8
         arr.add(8);
        //Ordeno el arreglo para tomar la posicion mas grande
        Collections.sort(arr); //Para ordenar elementos.
        for (int i = 0; i < arr.size(); i++) {
            System.out.println(arr.get(i));
        }
        textArea.append("Entro al grupo el proceso 8."+"\n");
        f8.setVisible(true);
        e8.setVisible(false);
        e8.setEnabled(true);
        t8.setText("Proceso 8");
        t8.setBackground(Color.WHITE);
    }//GEN-LAST:event_e8ActionPerformed

    private void e6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e6ActionPerformed
       // Entrar proceso 6
         arr.add(6);
        //Ordeno el arreglo para tomar la posicion mas grande
        Collections.sort(arr); //Para ordenar elementos.
        for (int i = 0; i < arr.size(); i++) {
            System.out.println(arr.get(i));
        }
        textArea.append("Entro al grupo el proceso 6."+"\n");
        f6.setVisible(true);
        e6.setVisible(false);
        e6.setEnabled(true);
        t6.setText("Proceso 7");
        t6.setBackground(Color.WHITE);
    }//GEN-LAST:event_e6ActionPerformed

    private void e5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e5ActionPerformed
        // Entrar proceso 5
         arr.add(5);
        //Ordeno el arreglo para tomar la posicion mas grande
        Collections.sort(arr); //Para ordenar elementos.
        for (int i = 0; i < arr.size(); i++) {
            System.out.println(arr.get(i));
        }
        textArea.append("Entro al grupo el proceso 5."+"\n");
        f5.setVisible(true);
        e5.setVisible(false);
        e5.setEnabled(true);
        t5.setText("Proceso 5");
        t5.setBackground(Color.WHITE);
    }//GEN-LAST:event_e5ActionPerformed

    private void e3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e3ActionPerformed
        // Entrar proceso 3
         arr.add(3);
        //Ordeno el arreglo para tomar la posicion mas grande
        Collections.sort(arr); //Para ordenar elementos.
        for (int i = 0; i < arr.size(); i++) {
            System.out.println(arr.get(i));
        }
        textArea.append("Entro al grupo el proceso 3."+"\n");
        f3.setVisible(true);
        e3.setVisible(false);
        e3.setEnabled(true);
        t3.setText("Proceso 3");
        t3.setBackground(Color.WHITE);
    }//GEN-LAST:event_e3ActionPerformed

    private void e2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e2ActionPerformed
        // Entrar proceso 2
         arr.add(2);
        //Ordeno el arreglo para tomar la posicion mas grande
        Collections.sort(arr); //Para ordenar elementos.
        for (int i = 0; i < arr.size(); i++) {
            System.out.println(arr.get(i));
        }
        textArea.append("Entro al grupo el proceso 2."+"\n");
        f2.setVisible(true);
        e2.setVisible(false);
        e2.setEnabled(true);
        t2.setText("Proceso 2");
        t2.setBackground(Color.WHITE);
    }//GEN-LAST:event_e2ActionPerformed

    private void e1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e1ActionPerformed
        // Entrar proceso 1
         arr.add(1);
        //Ordeno el arreglo para tomar la posicion mas grande
        Collections.sort(arr); //Para ordenar elementos.
        for (int i = 0; i < arr.size(); i++) {
            System.out.println(arr.get(i));
        }
        textArea.append("Entro al grupo el proceso 1."+"\n");
        f1.setVisible(true);
        e1.setVisible(false);
        e1.setEnabled(true);
        t1.setText("Proceso 1");
        t1.setBackground(Color.WHITE);
    }//GEN-LAST:event_e1ActionPerformed

    private void f6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f6ActionPerformed
        // fallo 6
          //Aqui se detecta que fallara 
        for (int i = 1; i <arr.size(); i++) {
            if(arr.get(i)==this.id) arr.remove(i);
        }
        textArea.append("Proceso 6 detecto el fallo."+"\n");
        //Aqui error ....
        //Todos los que esten afuera del grupo acticar entrada.
        //e7.setEnabled(true);
        textArea.append("El proceso "+this.id+" sale del grupo."+"\n");
        switch(this.id){
            case 1:{
                e1.setEnabled(true);
                  t1.setText("DESACTIVADO");
                  t1.setBackground(Color.RED);
                break;
            }
            case 3:{
                e3.setEnabled(true);
                  t3.setText("DESACTIVADO");
                  t3.setBackground(Color.RED);
                break;
            }
            case 4:{
                e4.setEnabled(true);
                  t4.setText("DESACTIVADO");
                  t4.setBackground(Color.RED);
                break;
            }
            case 5:{
                e5.setEnabled(true);
                  t5.setText("DESACTIVADO");
                  t5.setBackground(Color.RED);
                break;
            }
            case 6:{
                e6.setEnabled(true);
                  t6.setText("DESACTIVADO");
                  t6.setBackground(Color.RED);
                break;
            }
            case 2:{
                  e2.setEnabled(true);
                  t2.setText("DESACTIVADO");
                  t2.setBackground(Color.RED);
                break;
            }
            case 8:{
                e8.setEnabled(true);
                  t8.setText("DESACTIVADO");
                  t8.setBackground(Color.RED);
                break;
            }
            case 7:{
                e7.setEnabled(true);
                  t7.setText("DESACTIVADO");
                  t7.setBackground(Color.RED);
                break;
            }
        }
        //Ordeno el arreglo para tomar la posicion mas grande
        Collections.sort(arr); //Para ordenar elementos.
        for (int j = 6; j < arr.size(); j++) {
            //System.out.println(arr.get(j));
            textArea.append("El proceso "+arr.get(j)+" responde con OK."+"\n");
        }
        textArea.append("El proceso "+arr.get(arr.size()-1)+" es el nuevo cordinador."+"\n");
        switch(arr.get(arr.size()-1)){
            case 1:{
                id=1;
                t1.setText("CORDINADOR");
                t1.setBackground(Color.GREEN);
                f1.setVisible(false);
                 
                e1.setVisible(true);
                e1.setEnabled(false);
                break;
            }
            case 3:{
                id=3;
                t3.setText("CORDINADOR");
                t3.setBackground(Color.GREEN);
                f3.setVisible(false);
                e3.setVisible(true);
                e3.setEnabled(false);
                break;
            }
            case 4:{
                id=4;
                t4.setText("CORDINADOR");
                t4.setBackground(Color.GREEN);
                f4.setVisible(false);
                e4.setVisible(true);
                e4.setEnabled(false);
                break;
            }
            case 5:{
                id=5;
                t5.setText("CORDINADOR");
                t5.setBackground(Color.GREEN);
                f5.setVisible(false);
                e5.setVisible(true);
                e5.setEnabled(false);
                break;
            }
            case 6:{
                id=6;
                t6.setText("CORDINADOR");
                t6.setBackground(Color.GREEN);
                f6.setVisible(false);
                e6.setVisible(true);
                e6.setEnabled(false);
                break;
            }
            case 2:{
                id=2;
                t2.setText("CORDINADOR");
                t2.setBackground(Color.GREEN);
                f2.setVisible(false);
                e2.setVisible(true);
                e2.setEnabled(false);
                break;
            }
            case 8:{
                id=8;
                t8.setText("CORDINADOR");
                t8.setBackground(Color.GREEN);
                f8.setVisible(false);
                e8.setVisible(true);
                e8.setEnabled(false);
                break;
            } 
            case 7:{
                id=7;
                t7.setText("CORDINADOR");
                t7.setBackground(Color.GREEN);
                f7.setVisible(false);
                e7.setVisible(true);
                e7.setEnabled(false);
                break;
            } 
        }
        arr.remove(arr.size()-1);
    }//GEN-LAST:event_f6ActionPerformed

    private void f5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f5ActionPerformed
        // fallo 5
          //Aqui se detecta que fallara 
        for (int i = 1; i <arr.size(); i++) {
            if(arr.get(i)==this.id) arr.remove(i);
        }
        textArea.append("Proceso 5 detecto el fallo."+"\n");
        //Aqui error ....
        //Todos los que esten afuera del grupo acticar entrada.
        //e7.setEnabled(true);
        textArea.append("El proceso "+this.id+" sale del grupo."+"\n");
        switch(this.id){
            case 1:{
                e1.setEnabled(true);
                  t1.setText("DESACTIVADO");
                  t1.setBackground(Color.RED);
                break;
            }
            case 3:{
                e3.setEnabled(true);
                  t3.setText("DESACTIVADO");
                  t3.setBackground(Color.RED);
                break;
            }
            case 4:{
                e4.setEnabled(true);
                  t4.setText("DESACTIVADO");
                  t4.setBackground(Color.RED);
                break;
            }
            case 5:{
                e5.setEnabled(true);
                  t5.setText("DESACTIVADO");
                  t5.setBackground(Color.RED);
                break;
            }
            case 6:{
                e6.setEnabled(true);
                  t6.setText("DESACTIVADO");
                  t6.setBackground(Color.RED);
                break;
            }
            case 2:{
                  e2.setEnabled(true);
                  t2.setText("DESACTIVADO");
                  t2.setBackground(Color.RED);
                break;
            }
            case 8:{
                e8.setEnabled(true);
                  t8.setText("DESACTIVADO");
                  t8.setBackground(Color.RED);
                break;
            }
            case 7:{
                e7.setEnabled(true);
                  t7.setText("DESACTIVADO");
                  t7.setBackground(Color.RED);
                break;
            }
        }
        //Ordeno el arreglo para tomar la posicion mas grande
        Collections.sort(arr); //Para ordenar elementos.
        for (int j = 5; j < arr.size(); j++) {
            //System.out.println(arr.get(j));
            textArea.append("El proceso "+arr.get(j)+" responde con OK."+"\n");
        }
        textArea.append("El proceso "+arr.get(arr.size()-1)+" es el nuevo cordinador."+"\n");
        switch(arr.get(arr.size()-1)){
            case 1:{
                id=1;
                t1.setText("CORDINADOR");
                t1.setBackground(Color.GREEN);
                f1.setVisible(false);
                 
                e1.setVisible(true);
                e1.setEnabled(false);
                break;
            }
            case 3:{
                id=3;
                t3.setText("CORDINADOR");
                t3.setBackground(Color.GREEN);
                f3.setVisible(false);
                e3.setVisible(true);
                e3.setEnabled(false);
                break;
            }
            case 4:{
                id=4;
                t4.setText("CORDINADOR");
                t4.setBackground(Color.GREEN);
                f4.setVisible(false);
                e4.setVisible(true);
                e4.setEnabled(false);
                break;
            }
            case 5:{
                id=5;
                t5.setText("CORDINADOR");
                t5.setBackground(Color.GREEN);
                f5.setVisible(false);
                e5.setVisible(true);
                e5.setEnabled(false);
                break;
            }
            case 6:{
                id=6;
                t6.setText("CORDINADOR");
                t6.setBackground(Color.GREEN);
                f6.setVisible(false);
                e6.setVisible(true);
                e6.setEnabled(false);
                break;
            }
            case 2:{
                id=2;
                t2.setText("CORDINADOR");
                t2.setBackground(Color.GREEN);
                f2.setVisible(false);
                e2.setVisible(true);
                e2.setEnabled(false);
                break;
            }
            case 8:{
                id=8;
                t8.setText("CORDINADOR");
                t8.setBackground(Color.GREEN);
                f8.setVisible(false);
                e8.setVisible(true);
                e8.setEnabled(false);
                break;
            } 
            case 7:{
                id=7;
                t7.setText("CORDINADOR");
                t7.setBackground(Color.GREEN);
                f7.setVisible(false);
                e7.setVisible(true);
                e7.setEnabled(false);
                break;
            } 
        }
        arr.remove(arr.size()-1);
    }//GEN-LAST:event_f5ActionPerformed

    private void f3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f3ActionPerformed
        //fallo 3
          //Aqui se detecta que fallara 
        for (int i = 1; i <arr.size(); i++) {
            if(arr.get(i)==this.id) arr.remove(i);
        }
        textArea.append("Proceso 3 detecto el fallo."+"\n");
        //Aqui error ....
        //Todos los que esten afuera del grupo acticar entrada.
        //e7.setEnabled(true);
        textArea.append("El proceso "+this.id+" sale del grupo."+"\n");
        switch(this.id){
            case 1:{
                e1.setEnabled(true);
                  t1.setText("DESACTIVADO");
                  t1.setBackground(Color.RED);
                break;
            }
            case 3:{
                e3.setEnabled(true);
                  t3.setText("DESACTIVADO");
                  t3.setBackground(Color.RED);
                break;
            }
            case 4:{
                e4.setEnabled(true);
                  t4.setText("DESACTIVADO");
                  t4.setBackground(Color.RED);
                break;
            }
            case 5:{
                e5.setEnabled(true);
                  t5.setText("DESACTIVADO");
                  t5.setBackground(Color.RED);
                break;
            }
            case 6:{
                e6.setEnabled(true);
                  t6.setText("DESACTIVADO");
                  t6.setBackground(Color.RED);
                break;
            }
            case 2:{
                  e2.setEnabled(true);
                  t2.setText("DESACTIVADO");
                  t2.setBackground(Color.RED);
                break;
            }
            case 8:{
                e8.setEnabled(true);
                  t8.setText("DESACTIVADO");
                  t8.setBackground(Color.RED);
                break;
            }
            case 7:{
                e7.setEnabled(true);
                  t7.setText("DESACTIVADO");
                  t7.setBackground(Color.RED);
                break;
            }
        }
        //Ordeno el arreglo para tomar la posicion mas grande
        Collections.sort(arr); //Para ordenar elementos.
        for (int j = 3; j < arr.size(); j++) {
            //System.out.println(arr.get(j));
            textArea.append("El proceso "+arr.get(j)+" responde con OK."+"\n");
        }
        textArea.append("El proceso "+arr.get(arr.size()-1)+" es el nuevo cordinador."+"\n");
        switch(arr.get(arr.size()-1)){
            case 1:{
                id=1;
                t1.setText("CORDINADOR");
                t1.setBackground(Color.GREEN);
                f1.setVisible(false);
                 
                e1.setVisible(true);
                e1.setEnabled(false);
                break;
            }
            case 3:{
                id=3;
                t3.setText("CORDINADOR");
                t3.setBackground(Color.GREEN);
                f3.setVisible(false);
                e3.setVisible(true);
                e3.setEnabled(false);
                break;
            }
            case 4:{
                id=4;
                t4.setText("CORDINADOR");
                t4.setBackground(Color.GREEN);
                f4.setVisible(false);
                e4.setVisible(true);
                e4.setEnabled(false);
                break;
            }
            case 5:{
                id=5;
                t5.setText("CORDINADOR");
                t5.setBackground(Color.GREEN);
                f5.setVisible(false);
                e5.setVisible(true);
                e5.setEnabled(false);
                break;
            }
            case 6:{
                id=6;
                t6.setText("CORDINADOR");
                t6.setBackground(Color.GREEN);
                f6.setVisible(false);
                e6.setVisible(true);
                e6.setEnabled(false);
                break;
            }
            case 2:{
                id=2;
                t2.setText("CORDINADOR");
                t2.setBackground(Color.GREEN);
                f2.setVisible(false);
                e2.setVisible(true);
                e2.setEnabled(false);
                break;
            }
            case 8:{
                id=8;
                t8.setText("CORDINADOR");
                t8.setBackground(Color.GREEN);
                f8.setVisible(false);
                e8.setVisible(true);
                e8.setEnabled(false);
                break;
            } 
            case 7:{
                id=7;
                t7.setText("CORDINADOR");
                t7.setBackground(Color.GREEN);
                f7.setVisible(false);
                e7.setVisible(true);
                e7.setEnabled(false);
                break;
            } 
        }
        arr.remove(arr.size()-1);
    }//GEN-LAST:event_f3ActionPerformed

    private void f4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f4ActionPerformed
        //Fallo 4
          //Aqui se detecta que fallara 
        for (int i = 1; i <arr.size(); i++) {
            if(arr.get(i)==this.id) arr.remove(i);
        }
        textArea.append("Proceso 4 detecto el fallo."+"\n");
        //Aqui error ....
        //Todos los que esten afuera del grupo acticar entrada.
        //e7.setEnabled(true);
        textArea.append("El proceso "+this.id+" sale del grupo."+"\n");
        switch(this.id){
            case 1:{
                e1.setEnabled(true);
                  t1.setText("DESACTIVADO");
                  t1.setBackground(Color.RED);
                break;
            }
            case 3:{
                e3.setEnabled(true);
                  t3.setText("DESACTIVADO");
                  t3.setBackground(Color.RED);
                break;
            }
            case 4:{
                e4.setEnabled(true);
                  t4.setText("DESACTIVADO");
                  t4.setBackground(Color.RED);
                break;
            }
            case 5:{
                e5.setEnabled(true);
                  t5.setText("DESACTIVADO");
                  t5.setBackground(Color.RED);
                break;
            }
            case 6:{
                e6.setEnabled(true);
                  t6.setText("DESACTIVADO");
                  t6.setBackground(Color.RED);
                break;
            }
            case 2:{
                  e2.setEnabled(true);
                  t2.setText("DESACTIVADO");
                  t2.setBackground(Color.RED);
                break;
            }
            case 8:{
                e8.setEnabled(true);
                  t8.setText("DESACTIVADO");
                  t8.setBackground(Color.RED);
                break;
            }
            case 7:{
                e7.setEnabled(true);
                  t7.setText("DESACTIVADO");
                  t7.setBackground(Color.RED);
                break;
            }
        }
        //Ordeno el arreglo para tomar la posicion mas grande
        Collections.sort(arr); //Para ordenar elementos.
        for (int j = 4; j < arr.size(); j++) {
            //System.out.println(arr.get(j));
            textArea.append("El proceso "+arr.get(j)+" responde con OK."+"\n");
        }
        textArea.append("El proceso "+arr.get(arr.size()-1)+" es el nuevo cordinador."+"\n");
        switch(arr.get(arr.size()-1)){
            case 1:{
                id=1;
                t1.setText("CORDINADOR");
                t1.setBackground(Color.GREEN);
                f1.setVisible(false);
                 
                e1.setVisible(true);
                e1.setEnabled(false);
                break;
            }
            case 3:{
                id=3;
                t3.setText("CORDINADOR");
                t3.setBackground(Color.GREEN);
                f3.setVisible(false);
                e3.setVisible(true);
                e3.setEnabled(false);
                break;
            }
            case 4:{
                id=4;
                t4.setText("CORDINADOR");
                t4.setBackground(Color.GREEN);
                f4.setVisible(false);
                e4.setVisible(true);
                e4.setEnabled(false);
                break;
            }
            case 5:{
                id=5;
                t5.setText("CORDINADOR");
                t5.setBackground(Color.GREEN);
                f5.setVisible(false);
                e5.setVisible(true);
                e5.setEnabled(false);
                break;
            }
            case 6:{
                id=6;
                t6.setText("CORDINADOR");
                t6.setBackground(Color.GREEN);
                f6.setVisible(false);
                e6.setVisible(true);
                e6.setEnabled(false);
                break;
            }
            case 2:{
                id=2;
                t2.setText("CORDINADOR");
                t2.setBackground(Color.GREEN);
                f2.setVisible(false);
                e2.setVisible(true);
                e2.setEnabled(false);
                break;
            }
            case 8:{
                id=8;
                t8.setText("CORDINADOR");
                t8.setBackground(Color.GREEN);
                f8.setVisible(false);
                e8.setVisible(true);
                e8.setEnabled(false);
                break;
            } 
            case 7:{
                id=7;
                t7.setText("CORDINADOR");
                t7.setBackground(Color.GREEN);
                f7.setVisible(false);
                e7.setVisible(true);
                e7.setEnabled(false);
                break;
            } 
        }
        arr.remove(arr.size()-1);
    }//GEN-LAST:event_f4ActionPerformed

    private void f8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f8ActionPerformed
        // fallo 8
          //Aqui se detecta que fallara 
        for (int i = 1; i <arr.size(); i++) {
            if(arr.get(i)==this.id) arr.remove(i);
        }
        textArea.append("Proceso 7 detecto el fallo."+"\n");
        //Aqui error ....
        //Todos los que esten afuera del grupo acticar entrada.
        //e7.setEnabled(true);
        textArea.append("El proceso "+this.id+" sale del grupo."+"\n");
        switch(this.id){
            case 1:{
                e1.setEnabled(true);
                  t1.setText("DESACTIVADO");
                  t1.setBackground(Color.RED);
                break;
            }
            case 3:{
                e3.setEnabled(true);
                  t3.setText("DESACTIVADO");
                  t3.setBackground(Color.RED);
                break;
            }
            case 4:{
                e4.setEnabled(true);
                  t4.setText("DESACTIVADO");
                  t4.setBackground(Color.RED);
                break;
            }
            case 5:{
                e5.setEnabled(true);
                  t5.setText("DESACTIVADO");
                  t5.setBackground(Color.RED);
                break;
            }
            case 6:{
                e6.setEnabled(true);
                  t6.setText("DESACTIVADO");
                  t6.setBackground(Color.RED);
                break;
            }
            case 2:{
                  e2.setEnabled(true);
                  t2.setText("DESACTIVADO");
                  t2.setBackground(Color.RED);
                break;
            }
            case 8:{
                e8.setEnabled(true);
                  t8.setText("DESACTIVADO");
                  t8.setBackground(Color.RED);
                break;
            }
            case 7:{
                e7.setEnabled(true);
                  t7.setText("DESACTIVADO");
                  t7.setBackground(Color.RED);
                break;
            }
        }
        //Ordeno el arreglo para tomar la posicion mas grande
        Collections.sort(arr); //Para ordenar elementos.
        for (int j = 8; j < arr.size(); j++) {
            //System.out.println(arr.get(j));
            textArea.append("El proceso "+arr.get(j)+" responde con OK."+"\n");
        }
        textArea.append("El proceso "+arr.get(arr.size()-1)+" es el nuevo cordinador."+"\n");
        switch(arr.get(arr.size()-1)){
            case 1:{
                id=1;
                t1.setText("CORDINADOR");
                t1.setBackground(Color.GREEN);
                f1.setVisible(false);
                 
                e1.setVisible(true);
                e1.setEnabled(false);
                break;
            }
            case 3:{
                id=3;
                t3.setText("CORDINADOR");
                t3.setBackground(Color.GREEN);
                f3.setVisible(false);
                e3.setVisible(true);
                e3.setEnabled(false);
                break;
            }
            case 4:{
                id=4;
                t4.setText("CORDINADOR");
                t4.setBackground(Color.GREEN);
                f4.setVisible(false);
                e4.setVisible(true);
                e4.setEnabled(false);
                break;
            }
            case 5:{
                id=5;
                t5.setText("CORDINADOR");
                t5.setBackground(Color.GREEN);
                f5.setVisible(false);
                e5.setVisible(true);
                e5.setEnabled(false);
                break;
            }
            case 6:{
                id=6;
                t6.setText("CORDINADOR");
                t6.setBackground(Color.GREEN);
                f6.setVisible(false);
                e6.setVisible(true);
                e6.setEnabled(false);
                break;
            }
            case 2:{
                id=2;
                t2.setText("CORDINADOR");
                t2.setBackground(Color.GREEN);
                f2.setVisible(false);
                e2.setVisible(true);
                e2.setEnabled(false);
                break;
            }
            case 8:{
                id=8;
                t8.setText("CORDINADOR");
                t8.setBackground(Color.GREEN);
                f8.setVisible(false);
                e8.setVisible(true);
                e8.setEnabled(false);
                break;
            } 
            case 7:{
                id=7;
                t7.setText("CORDINADOR");
                t7.setBackground(Color.GREEN);
                f7.setVisible(false);
                e7.setVisible(true);
                e7.setEnabled(false);
                break;
            } 
        }
        arr.remove(arr.size()-1);
    }//GEN-LAST:event_f8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BullyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BullyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BullyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BullyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BullyFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton c1;
    private javax.swing.JButton c2;
    private javax.swing.JButton c3;
    private javax.swing.JButton c4;
    private javax.swing.JButton c5;
    private javax.swing.JButton c6;
    private javax.swing.JButton c7;
    private javax.swing.JButton c8;
    private javax.swing.JButton e1;
    private javax.swing.JButton e2;
    private javax.swing.JButton e3;
    private javax.swing.JButton e4;
    private javax.swing.JButton e5;
    private javax.swing.JButton e6;
    private javax.swing.JButton e7;
    private javax.swing.JButton e8;
    private javax.swing.JButton f1;
    private javax.swing.JButton f2;
    private javax.swing.JButton f3;
    private javax.swing.JButton f4;
    private javax.swing.JButton f5;
    private javax.swing.JButton f6;
    private javax.swing.JButton f7;
    private javax.swing.JButton f8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables

}
